# Generated by Django 4.1 on 2024-10-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='searched_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='query',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='term',
            field=models.CharField(default='未指定', max_length=255),
            preserve_default=False,
        ),
    ]
